version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - .:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
