version: '3.8'

services:
  backend:
    build: .
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - HOST=0.0.0.0
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - LOG_LEVEL=DEBUG  # 로깅 레벨 설정
    volumes:
      - .:/app
      - ./logs:/app/logs  # 로그 파일 저장을 위한 볼륨
    command: python start.py
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # 로그 파일 최대 크기
        max-file: "3"    # 보관할 로그 파일 개수
        tag: "{{.Name}}"
        labels: "backend-logs"