[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1
minReplicas = 1
maxReplicas = 1

[deploy.envs]
PYTHON_VERSION = "3.11.7"
PORT = "7000"
HOST = "0.0.0.0"
RAILWAY_ENVIRONMENT = "production"
CORS_ORIGINS = "https://finance-dashboard-git-main-jeongtaeyeongs-projects.vercel.app,https://finance-dashboard.vercel.app"

[[deploy.services]]
name = "backend"
protocol = "http"
internal_port = "7000"
auto_start = true
auto_stop = false

[[deploy.mounts]]
source = "/data"
destination = "/app/data"
type = "volume"