[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
PYTHON_VERSION = "3.11.7"
PORT = "7000"
HOST = "0.0.0.0"