[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 7000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "7000"
HOST = "0.0.0.0"
DB_NAME = "project1_db"
