[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
minReplicas = 1
maxReplicas = 1

[deploy.envs]
RAILWAY_ENVIRONMENT = "production"
PORT = "7000"
HOST = "0.0.0.0"
CHROME_BIN = "/usr/bin/google-chrome"
CHROMEDRIVER_PATH = "/usr/local/bin/chromedriver"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
CORS_ORIGINS = "https://finance-dashboard-git-main-jeongtaeyeongs-projects.vercel.app,https://finance-dashboard.vercel.app"

[[deploy.services]]
name = "backend"
protocol = "http"
internal_port = "7000"
auto_start = true
auto_stop = false

[[deploy.mounts]]
source = "/data"
destination = "/app/data"
type = "volume"